### ISSUE TITLE
Broken links in prompt format docs

### ISSUE THREAD

**Issue by msaroufim** [meta-llama/llama-models#91]
In this blog post there are 2 links for the prompt format that are broken https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/ so it's clear where instructions are to generate the prompt formats (where it says here)

https://github.com/meta-llama/llama-models/blob/main/models/llama3/generation.py
https://github.com/meta-llama/llama-models/blob/main/models/llama3/tokenizer.py
<img width="972" alt="Screenshot 2024-08-05 at 1 48 10 PM" src="https://github.com/user-attachments/assets/7e10cc9f-2c74-4fbd-890e-c05275194331">

**Comment by HamidShojanazeri** [comment]
Thanks @msaroufim for the pointer, team is looking at updating the links.

**Comment by msaroufim** [comment]
Thanks @HamidShojanazeri fwiw might be worth checking how up to date that page is because even the code block should probably be `<|begin_of_text|>{{ user_message }}<|end_of_text|>`

**Comment by karpathy** [comment]
Thank you @msaroufim , also if possible could the docs clarify what they mean by the newlines as part of the prompt format? It's possible the updated links will clarify as well, but the comment (as is) feels unclear right now.

**Comment by albertodepaola** [comment]
@msaroufim and @karpathy, thanks for the feedback! We will update with the correct links, in the mean time, here are the corrected references:
- for the instruct model, this [method](https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py#L222) correctly formats a [Dialog](https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py#L35) sequence
- for the base model, the only config necessary is to call the tokenizer encode with `bos=True` and `eos=False`, as shown [here](https://github.com/meta-llama/llama3/blob/main/llama/generation.py#L260).

On the newlines, the idea was to highlight that the format expects those newlines to be there, as shown [here](https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py#L211). We will update as well to make it clear, as this applies to both llama 3 and 3.1.

**Comment by jspisak** [comment]
thanks @karpathy for pointing these out - really appreciate the sharp eyes..

**Comment by ashwinb** [comment]
Hey @karpathy, thanks for pointing out the issues in our documentation. We will fix them. In addition, we are capturing details about the models directly in code since it is sometimes hard to convey nuances in documentation. While reading code is the best, we are also looking to make it easier. So, we have been working on the llama CLI that shows a lot of these details about the model by running the actual code for tokenization. 

You can get the llama CLI by running

```
pip install llama-toolchain
```

With the CLI, you can now get more details about the models themselves by running

```
# get the list of models
llama model list

# describe the models
llama model describe -m <model-id>

# list all the prompt templates
llama model template

# get specific templates
llama model template --name <template-name>
```

Would love to get your thoughts on this approach.

**Comment by karpathy** [comment]
@albertodepaola Thank you I like reference code a lot more than text docs because it is a lot more precise, so thank you for the pointers on how the Chat object is rendered. For the base model, I think this documentation is slightly incomplete/misleading because my goal is not to prompt the model but to render training examples for finetuning the base model. My question is: are both BOS and EOS used to render training examples in the pretraining data? Based on sampling from the base model, I suspect this is the token sequence: <BOS>document1<EOS><BOS>document2<EOS>..., but I don't believe I see this documented very well in the original page. In particular note that <EOS><BOS> are both used, which is possibly a bit wasteful of the sequence space because one could in principle get away with using a single delimiting token for base model pretraining, i.e. <EOT>document1<EOT>document2<EOT>document3<EOT>document4 etc...

@ashwinb My preference would be reference code, similar to the urls pointed to by @albertodepaola, which is a lot more concrete than any English paragraph can be. An object that defines the protocol, e.g. `Dialog`, then a very simple, readable, dependency-free code to `render` a Dialog into token sequence - separately for both prompting and serialization of a full Dialog, and for both base and chat. I'd make it something people can either easily import or even copy paste. But text documentation can supplement with more instructions, e.g. the reasoning behind both BOS/EOS.

One thing I don't like about `pip install llama-toolchain` for this specific Issue is that I shouldn't have to install all of:

Successfully installed Pillow-10.4.0 accelerate-0.33.0 aiohappyeyeballs-2.3.4 aiohttp-3.10.1 aiosignal-1.3.1 antlr4-python3-runtime-4.9.3 async-timeout-4.0.3 black-24.4.2 boltons-21.0.0 bracex-2.5 cfgv-3.4.0 click-8.1.7 click-option-group-0.5.6 codeshield-1.0.1 colorama-0.4.6 contourpy-1.2.1 cycler-0.12.1 defusedxml-0.7.1 deprecated-1.2.14 distlib-0.3.8 face-22.0.0 fastapi-0.112.0 flake8-7.1.1 fonttools-4.53.1 frozenlist-1.4.1 glom-22.1.0 googleapis-common-protos-1.63.2 h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 hydra-core-1.3.2 hydra-zen-0.13.0 identify-2.6.0 importlib-metadata-7.1.0 kiwisolver-1.4.5 libcst-1.4.0 llama-toolchain-0.0.2 markdown-it-py-3.0.0 matplotlib-3.9.0 mccabe-0.7.0 mdurl-0.1.2 moreorless-0.4.0 multidict-6.0.5 mypy-extensions-1.0.0 nodeenv-1.9.1 omegaconf-2.3.0 opentelemetry-api-1.25.0 opentelemetry-exporter-otlp-proto-common-1.25.0 opentelemetry-exporter-otlp-proto-http-1.25.0 opentelemetry-instrumentation-0.46b0 opentelemetry-instrumentation-requests-0.46b0 opentelemetry-proto-1.25.0 opentelemetry-sdk-1.25.0 opentelemetry-semantic-conventions-0.46b0 opentelemetry-util-http-0.46b0 packaging-24.1 pandas-2.2.2 pathspec-0.12.1 peewee-3.17.6 platformdirs-4.2.2 pre-commit-3.8.0 protobuf-4.25.4 psutil-6.0.0 pycodestyle-2.12.1 pyflakes-3.2.0 pygments-2.18.0 pyparsing-3.1.2 python-dotenv-1.0.1 python-openapi-0.1.9 pytz-2024.1 rich-13.7.1 ruamel.yaml-0.17.40 ruamel.yaml.clib-0.2.8 semgrep-1.83.0 starlette-0.37.2 stdlibs-2024.5.15 toml-0.10.2 tomlkit-0.13.0 trailrunner-1.4.0 tzdata-2024.1 ufmt-2.7.0 usort-1.0.8 uvicorn-0.30.5 virtualenv-20.26.3 wcmatch-8.5.2 wrapt-1.16.0 yarl-1.9.4 zipp-3.19.2 zmq-0.0.0

just to get docs on the tokenization format.

**Comment by ashwinb** [comment]
Yeah point taken about llama-toolchain’s deps. We are working on splitting into a very lightweight llama-cmdline package. Will also make the tokenization utils easier to copy paste into downstream code.

**Comment by ashwinb** [comment]
@karpathy Got the dependency list for `llama-toolchain` down to this now

```
fire
httpx
huggingface-hub
jinja2
pydantic==1.10.13
pydantic_core==2.18.2
PyYAML
requests
tiktoken
```

Huggingface -> for downloading models
Yaml + jinja2 -> for prompt templates and some config

Hopefully this is _much_ more palatable.

**Comment by albertodepaola** [comment]
Quick update on the documentation, the broken links where updated.
